miniblog/urls.py
from django.contrib import admin
from django.urls import path
from blog import views
from . import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('logout/', views.user_logout, name='logout'),
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('addpost/', views.add_post, name='addpost'),
    path('updatepost/<int:id>/', views.update_post, name='updatepost'),
    path('delete/<int:id>/', views.delete_post, name='deletepost'),











]
# Serve static files during development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=(150))
    desc = models.TextField()

    

blog/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _
from .models import Post


class SignupForm(UserCreationForm):
 password1 = forms.CharField(label='Password',widget=forms.PasswordInput(attrs=
 {'class':'form-control'}))
 password2 = forms.CharField(label='Confirm password(again)',widget=forms.PasswordInput(attrs=
 {'class':'form-control'}))
 class Meta:
  model = User
  fields = ['username','first_name', 'last_name', 'email']
  labels = {'first_name': 'First Name','last_name': 'Last Name', 'email': 'Email'}


  widgets = {'username':forms.TextInput(attrs={'class':'form-control'}),
 'first_name':forms.TextInput(attrs={'class':'form-control'}),
 'last_name':forms.TextInput(attrs={'class':'form-control'}),
 'email':forms.EmailInput(attrs={'class':'form-control'}),
}
  
#Login
  
class LoginForm(AuthenticationForm):
 username = UsernameField(widget=forms.TextInput(attrs={'autofocus': True,'class':'form-control'}))
 password = forms.CharField(label=_("password"), strip=False,widget=forms.PasswordInput(attrs={'autocomplete':
 'current -password', 'class':'form-control'}))



class PostForm(forms.ModelForm): 
  class Meta:
    model = Post
    fields = ("title", 'desc')
    labels = {'title':'title', 'desc':'Description'}
    widgets = {'title':forms.TextInput(attrs=
    {'class':'from-control'}),
    'desc':forms.Textarea(attrs={'class':'form-control'}),}
 

blog/views.py
from django.shortcuts import render, HttpResponseRedirect
from .forms import SignupForm, LoginForm, PostForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from .models import Post
from django.contrib.auth.models import Group



# Create your views here.
# HOME
def home(request):
    posts = Post.objects.all()
    return render(request, 'blog/home.html', {'posts':posts})
# About

def about(request):
    return render(request, 'blog/about.html')

#Contact

def contact(request):
    
    return render(request, 'blog/contact.html',)


#Dashboard

def dashboard(request):
 if request.user.is_authenticated:
  posts = Post.objects.all()
  user = request.user
  full_name = user.get_full_name()
  gps = user.groups.all()
  return render(request, 'blog/dashboard.html', {'posts':posts,
  'full_name':full_name, 'groups':gps})
 else:
   return HttpResponseRedirect('/login/')

#Logout

def user_logout(request):
    logout(request)
    return HttpResponseRedirect('/')
    

#Signup

def user_signup(request):
 if request.method == 'POST':
  form = SignupForm(request.POST)
  if form.is_valid():
    messages.success(request, "Congratulation !! You Have Become An Author ")
    user = form.save()
    group = Group.objects.get(name='Author')
    user.groups.add(group)

 else:
    form = SignupForm()
 return render(request, 'blog/signup.html', {'form':form})


#Logindef user_login (request):
def user_login(request):
 if not request.user.is_authenticated:
  if request.method =="POST":
   form = LoginForm(request=request, data=request.POST )
   if form.is_valid():
    uname = form.cleaned_data['username']
    upass = form.cleaned_data['password']
    user = authenticate(username=uname, password=upass)
    if user is not None:
     login(request, user)
     messages.success(request, "Logged in Successfully !!")
     return HttpResponseRedirect('/dashboard/')
  else:
    form = LoginForm()
  return render(request, 'blog/login.html', {'form':form})
 else:
   return HttpResponseRedirect('/dashboard/')
 

   #Add New Post
def add_post(request):
  if request.user.is_authenticated:
    if request.method == 'POST':
     form = PostForm(request.POST)
     if form.is_valid():
      title = form.cleaned_data['title']
      desc = form.cleaned_data['desc']
      pst = Post(title=title, desc=desc)
      pst.save()
      messages.success(request, 'Post added successfully!')

      form = PostForm()
    else:
      form = PostForm()
    return render(request, "blog/addpost.html", {'form':form}) 
  else:
    return HttpResponseRedirect('/login/')   



#Update New Post

def update_post(request, id):
  if request.user.is_authenticated:
    if request.method == 'POST':
      pi = Post.objects.get(pk=id)
      form = PostForm(request.POST, instance=pi)
      if form.is_valid():
        form.save()
        messages.success(request, 'Post Edit successfully!')


        
    else:
      pi = Post.objects.get(pk=id)
      form = PostForm(instance=pi)
    return render(request, "blog/updatepost.html", {'form':form}) 
  else:
    return HttpResponseRedirect('/login/')   
  
  
  # Delete post

def delete_post(request, id):
  if request.user.is_authenticated:
    if request.method == "POST":
      pi = Post.objects.get(pk=id)
      pi.delete()
    return HttpResponseRedirect('/dashboard/')
  else:
    return HttpResponseRedirect('/login/')   

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5">Aboute Page</h3>
<p>Hello Sir,

    The MiniBlog Project is a lightweight and efficient blogging platform designed to provide users with a simple way to create, manage, and share blog posts.
    Developed using Django (Python) for the backend, HTML, CSS, and Bootstrap for the frontend, this project demonstrates a seamless integration of modern
    web technologies to deliver an intuitive user experience.</p>
    <p>Key Features:
        User-Friendly Interface:
        A clean and responsive design ensures easy navigation and accessibility across devices. 
       <p> CRUD Functionality:
        Users can create, read, update, and delete blog posts efficiently.</p>
        
       <p> Database Integration:
        Utilizes Django's ORM to manage and store user data securely.</p>
        
       <p> Bootstrap Styling:
        Incorporates Bootstrap components for a visually appealing layout and responsive design.</p>
        
       <p>Dynamic Content Management:
        Blogs are dynamically displayed, providing an interactive browsing experience for users.</p>
        
        <p>Customizable Templates:
        Custom HTML templates allow for flexible design and content management.</p>
        
        <p>Purpose:
        The MiniBlog Project is perfect for beginners to learn and explore the fundamentals of web development using Django and frontend technologies.
        It also serves as a foundation for building more complex web applications.</p>
        
       <p>Technology Stack:
        Backend: Django (Python)
        Frontend: HTML, CSS, Bootstrap
        Database: SQLite (default Django database)
        This project is an excellent demonstration of how to create a functional and visually appealing web application while adhering to industry best practices.</p>
        
        
        
        
        
        
        
        </p>


</div>

{% endblock content %}

blog/templates/blog/addpost.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
    <h3 class="text-white my-5">Dashboard / Add Post</h3>

    <!-- Display success or error messages -->
    {% if messages %}
    <div class="alert alert-info">
        <ul>
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    </div>
    {% endif %}

    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Add" class="btn btn-success">
        <a href="{% url "dashboard" %}" class="btn btn-danger">Cancel</a>
    </form>
</div>
{% endblock content %}

blog/templates/blog/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "blog/css/bootstrap.css" %}">
    <link rel="stylesheet" href="{% static "blog/css/style.css" %}">

    <title>Document</title>
</head>
<body>
    <div class="container-fluid bg-dark">
    {% include "blog/navbar.html" %}
    </div>
    <div class="container">
    <div class="row">
    <div class="col-sm-12">
        {% block msg  %}
        {% endblock msg %}
    </div>
    </div>

    <div class="row">
        {% block side %}
        {% endblock side %}
        
        {% block content %}
        {% endblock content %}

    </div>
    </div>


    <script src="{% static "blog/js/jQuery.js" %}"></script>
    <script src="{% static "blog/js/popper.js" %}"></script>
    <script src="{% static "blog/js/bootstrap.js" %}"></script>




</body>
</html>

blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5">Contact Page</h3>

<div class="container mt-5">
    <h1 class="text-warning mb-5 border-bottom">Contact</h1>
    <div class="row text-white mb-5">
    <p class="mx-auto mb-5">
        Do you have question? please do not hesitate to 
        contact. I will come back to you within a matter of hours
        to help you.
    </p>
    <div class="col-sm-9 mb-5">
        <form action="">
            <div class="form-row">
            <div class="form-group col-md-6">
            <label for="inputName">Your Name</label>
            <input type="text" class="form-control"
            id="inputName" />
            </div>
            <div class="form-group col-md-6">
            <label for="inputEmail">Your Email *</label>
            <input type="text" class="form-control"
            id="inputEmail" required />
            </div>
            </div>
    
            <div class="form-group">
            <label for="inputSubject">Your Subject</label>
            <input type="text" class="form-control"
            id="inputSubject"/>
    
    
            </div>
    
            <div class="mb-3">
            <label for="inputTextarea">Your massage *</label>
            <textarea class="form-control" id="inputTextarea"
            required></textarea>
    
            </div>
    
            <button class="btn btn-primary" type="submit">send</button>
            </form>
            </div>
            <div class="col-sm-3 text-center">
            <ul class="list-unstyled">
            <li>
            <i class="fas fa-map-market-alt fa-2x i-colo"></i>
            <p>India, Mumbai, maharashtra</p>
            </li>
            <li>
             <i class="fas fa-phone mt-4 fa-2xl i-colo"></i>  
             <p>+91 8459555107</p> 
            </li>
            <li>
                <i class="fas fa-envelope mt-4 fa-2xl i-colo"></i>
                <p>wasimahmadansari01@gmail.com</p>
            </li>
            </ul>
    
            </div>
    
    </div>
    
    </div>
    <div class="text-center">
    <a href="#" target="_blank"><i class="fab fa-twitter i-colo
        mr-3"></i></a>
    
        <a href="#" target="_blank"><i class="fab fa-dribbble
        i-colo mr-3"></i></a>
        <a href="#" target="_blank"><i class="fab fa-instagram
        i-colo"></i></a>
        <a href="#" target="_blank"><i class="fab fa-facebook-f
        i-colo"></i></a>
        
    </div>
</div>

{% endblock content %}

blog/templates/blog/dashboard.html
{% extends "blog/base.html" %}
{% load static %}

{% block msg %}
    {% if messages %}
    {% for message in messages %}
     <div {% if message.tags %} class="alert alert-{{message.tags}} alert-dismissible fade show" {% endif %}>
      <strong>{{message}}</strong>
      <button type="button" class="close" data-dismiss="alert"
      aria-label="close">
       <span aria-hidden="true">&times</span>
     </button>
     </div>
  {% endfor %}
  {% endif %}
{% endblock msg %}
    
{% block side %}
<div class="col-sm-2 text-white my-5 text-center">
  <h4 class="my-5">Profile</h4>
  <h5>{{full_name}}</h5>
  {% for group in groups %}
    <p>{{group.name}}</p>
  {% endfor %}
</div>
{% endblock side %}







{% block content %}
<div class="col-sm-10">
<h3 class="text-white my-5">Dashboard Page</h3>
<a href="{% url "addpost" %} " class="btn btn-success">Add Post</a>
<h4 class="text-center alert alert-info mt-3">Show Post Information</h4>
 {% if posts %}
  <table class="table table-hover bg-white">
    <thead>
      <tr class="text-center">
        <th scope="col" style="width:2%">ID</th>
        <th scope="col" style="width:28%">Title</th>
        <th scope="col" style="width:55%">Description</th>
        <th scope="col" style="width:15%">Action</th>
      </tr>
    </thead>
    <tbody>
     {% for post in posts %}
      <tr>
        <th scope="row">{{post.id}}</th>
        <td>{{post.title}}</td>
        <td>{{post.desc}}</td>
        <td class="text-center">
        
         {% if perms.blog.change_post %}
         <a href="{% url "updatepost" post.id %}" class="btn btn-warning btn-sm">Edit</a>
         {% if perms.blog.delete_post %}




         <form action="{% url "deletepost" post.id %}" method="post" class="d-inline">{% csrf_token %}
          <input type="submit" class="btn btn-danger btn-sm"
          value="Delete">
         </form>
         {% endif %}
         {% endif %}
        </td>
      </tr>
     {% endfor %}
    </tbody>
  </table>
  {% else %}
   <h4 class="text-center alert alert-warning">No Records</h4>
 {% endif %}


</div>
{% endblock content %}

blog/templates/blog/home.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5">Home Page</h3>
{% for post in posts %}
<div class="jumbotron jumbotron-fluid jumbo-color">
    <div class="container">
      <h1 class="display-4 font-weight-bold">{{post.title}}</h1>
      <p class="lead">{{post.desc}} </p>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock content %}

blog/templates/blog/login.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5">Login Page</h3>
<form action="" method="POST" novalidate>
 {% csrf_token %}
 {% for fm in form %}
 <div class="form-group">
   {{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
 </div>
 {% endfor %}
 <input type="submit" class="btn btn-primary" value="Login">
 {% if form.non_field_errors  %}
  {% for error in form.non_field_errors %}
   <p class="alert alert-danger my-3">{{error}}</p>
  {% endfor %}
 {% endif %}

</form>

</div>

{% endblock content %}

blog/templates/blog/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Mini Blog</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "about" %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "contact" %}">Contact</a>
        {% if request.user.is_authenticated %}
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "dashboard" %}">Dashboard</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "logout" %}">Logout</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url "signup" %}">Signup</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url "login" %}">Login</a>
        </li>
        {% endif %}
        
      </ul>
    </div>
  </div>
</nav>

blog/templates/blog/signup.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}

<div class="col-sm-10">
<h3 class="text-white my-5">Become an Author</h3>
{% if messages %}
{% for message in messages %}
<p {% if message.tags %} class="alert alert-{{message.tags}}
mb-5"{% endif %}>{{message}}</p>

{% endfor %}
{% endif %}

<form action="" method="POST" novalidate>
{% csrf_token %}
{% for fm in form %}
<div class="form-group">
{{fm.label_tag}} {{fm}} <small class="text-warning">{{fm.errors|striptags}}</small>
</div>
{% endfor %}
<input type="submit", value="Submit" class="btn btn-primary">
{% if form.non_field_errors %}
 {% for error in form.non_field_errors %}
   <p class="alert alert-danger my-3">{{error}}</p>
   {% endfor %}
  {% endif %}
</form>
</div>

{% endblock content %}

blog/templates/blog/updatepost.html
{% extends "blog/base.html" %}
{% load static %}
{% block content %}
<div class="col-sm-10">
<h3 class="text-white my-5">Dashboard/ Update Post</h3>

{% if messages %}
  <ul class="messages">
    {% for message in messages %}
      <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
  </ul>
{% endif %}






<form action="" method="post" novalidate>
 {% csrf_token %}
 {{form.as_p}}
 <input type="submit" value="Update" class="btn btn-success">



 <a href="{% url "dashboard" %}" class="btn btn-danger">Cancel</a>

</form>


</div>

{% endblock content %}